trigger:
- main  # Trigger when code is pushed to the 'main' branch

pool:
  name: Default  # Use your self-hosted agent pool

steps:
- script: echo "Hello, World!"
  displayName: 'Print Hello World'
